### ISSUE TITLE
Updates to align with Camtrap DM, batch 1

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#133]
First batch of suggested updates to improve usefulness for Wildlife Insights and eMammal, as discussed with @kbubnicki and @ben-norton:

## metadata

- [x] license: already in Frictionless, but indicate on metadata page
- [x] project > path: add as non-required property: #136
- [x] citation: add from Frictionless or Dublin Core:  #137
- [x] rightsholder: add from Frictionless or Dublin Core:  #137
- [x] information_withheld: add at _package_ level: wontfix, see #135
- [x] methods: drop field, that info should be included in project description: #139 
- [x] bait_use: drop field, too much possibility with conflict at deployment level: #140 

## obs

- [x] coordinate_uncertainty_in_meters: add in observations: #162

## dep

- [x] camera_height: change from centimeters to meters: #141
- [ ] detection_distance: add to deployments as maximum detection distance in meters, see #6

**Comment by peterdesmet** [comment]
There is only one remaining task, which is described in #6. Closing here.
