### ISSUE TITLE
Updated to align with Camtrap DM, batch 2

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#153]
- [x] camera_angle: Indicate this is vertical: #157
- [x] camera_heading/direction: Add, for horizontal orientation: #157
- [x] session: Update definition to highlight temporal aspect, mention tags: #159
- [x] array: Update definition to highlight spatial aspect (incl grid), mention tags: #159
- [x] tags: Review definition **Definition is ok**
- [x] add thumbnail_path: create issue: #155
- [x] favourite (or highlight): new boolean for multimedia: #158
- [x] observation_type: undefined -> unknown: #161
- [x] observation_type: empty -> blank: #161
- [x] taxonomic scope: add rank: #154
- [x] taxonomic scope: add taxon_id_reference per taxon, remove at taxonomic scope level: #154

```
{
  "taxon_id": "3Z5",
  "scientific_name": "Rodentia",
  "rank": "class",
  "taxon_id_reference": "Catalogue of Life",
  "vernacular_names": {
    "en": "rodents",
    "nl": "knaagdieren"
  }
}
```

**Comment by peterdesmet** [comment]
All suggested changes have been implemented.
