### ISSUE TITLE
Checklist for release v1.0

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#327]
## Issues

- [x] Resolve all issues in https://github.com/tdwg/camtrap-dp/milestone/1
- [x] Close milestone

## Home page

- [x] Remove notice on homepage
- [x] Remove `upcoming release` from IPT #364 
- [x] Update example to `1.0` #366 

## Code

- [x] Bump version
- [x] Create GitHub release: https://github.com/tdwg/camtrap-dp/releases/edit/untagged-403c2fb65980ea0f975d
- [x] Run tests
